### ISSUE TITLE
`gh_link.yaml` prescription deleted with GitHub link still active

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/prescriptions-refresh-job#118]
**Describe the bug**

The `gh_link.yaml` prescription for the `pydata-sphinx-theme` package was identified as a prescription to delete because of the project link inactivity, but the link is still active and has not changed (see https://github.com/thoth-station/prescriptions/pull/18664).

**To Reproduce**

Go to the GitHub project link specified in https://github.com/thoth-station/prescriptions/pull/18664/files and see it has not changed and is still active.

**Expected behavior**

The prescription is not identified as one to delete.

**Additional context**

Given the implementation of the [`gh_link.py`](https://github.com/thoth-station/prescriptions-refresh-job/blob/d6400ad820621380c9a4a0dd33a97d0028e89204/thoth/prescriptions_refresh/handlers/gh_link.py#L88) handler, this issue could be caused by the project GitHub page being temporarily unavailable, resulting in a status code `!= 200` and in the prescription deletion. A solution could be to perform a second check after a time interval to verify if the resource is still unavailable.

**Comment by mayaCostantini** [comment]
Closed by https://github.com/thoth-station/prescriptions-refresh-job/pull/119
/close

**Comment by mayaCostantini** [comment]
This issue is still happening after the fix proposed. From the logs generated when testing locally, the issue could be caused partly because of a `429` response status code (too many requests) when trying to get the URL of some repositories:

```
2022-03-20 15:57:46,149 938618 DEBUG    thoth.prescriptions_refresh.handlers.gh_link:126: 'https://github.com/apache/airflow' is an invalid GitHub URL based on HTTP status code 429
```
(Example of corresponding deleted prescription [here](https://github.com/thoth-station/prescriptions/pull/19791/files)).

Which causes the corresponding project prescription to be deleted because [the handler logic classifies the URL as invalid](https://github.com/thoth-station/prescriptions-refresh-job/blob/a2f7ca682e13ece3db4590d89592af0cc3bccd89/thoth/prescriptions_refresh/handlers/gh_link.py#L191-L198). Maybe we should consider handling this status code differently.

/reopen

**Comment by mayaCostantini** [comment]
The `429` status code issue might be caused by a large number of requests to the same link consecutively. If we take the example above, the GitHub project `apache/airflow` is hosting a large number of packages as we can see here with `apache-airflow-providers-*` packages: https://github.com/thoth-station/prescriptions/tree/master/prescriptions/ap_/

Maybe introducing a few seconds of latency between requests for packages hosted on the same GitHub project would solve the issue? @fridex wdyt?

**Comment by fridex** [comment]
My wild guess: this issue might be caused when prescriptions-refresh-job exceeds API rate limits. We could try to fix https://github.com/thoth-station/prescriptions-refresh-job/issues/130 to see if that helps.

**Comment by mayaCostantini** [comment]
Closing this issue as we haven't encounter it during last prescriptions refreshes. Feel free to reopen if needed.
