### ISSUE TITLE
thoth-prescriptions-refresh for thoth image analysis fails to start

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions-refresh-job#121]
**Describe the bug**

```
c logs prescriptions-refresh-image-analysis-h2lgx -c main                 
2022-02-28 19:53:34,739   1 INFO     thoth.common:319: Setting up logging to a Sentry instance 'sentry.io/1298083', environment 'ocp4-stage' and integrations ['SqlalchemyIntegration', 'AioHttpIntegration']
2022-02-28 19:53:34,842   1 INFO     thoth.common:366: Logging to rsyslog endpoint is turned off
Usage: thoth-prescriptions-refresh [OPTIONS] COMMAND [ARGS]...
Try 'thoth-prescriptions-refresh --help' for help.

Error: No such command 'thoth-image-analysis'.
```

**To Reproduce**
1. See stage cronworkflow deployment

**Comment by codificat** [comment]
/triage accepted

Is this due to a wrong/old version deployed maybe? hmm... a quick look at thoth-application suggests the latest version v0.6.0 is already in use...

In any case, this sounds
/priority critical-urgent
to me... feel free to correct

**Comment by codificat** [comment]
it seems prow had a glitch in receiving notifications, trying again:
/triage accepted
/priority critical-urgent

**Comment by codificat** [comment]
once more (sorry for the noise):
/triage accepted
/priority critical-urgent

**Comment by codificat** [comment]
ok, now prow should be working and get the labels:
/triage accepted
/priority critical-urgent

**Comment by shreekarSS** [comment]
I tried to run thoth-prescriptions-refresh cli in local env to check  if cli is valid. 

[sshreeka@fedora prescriptions-refresh-job]$ PYTHONPATH=. pipenv run python3 ./thoth-prescriptions-refresh thoth-image-analysis
2022-11-04 13:27:23,162 160015 WARNING  thoth.common:340: Logging to a Sentry instance is turned off
2022-11-04 13:27:23,166 160015 INFO     thoth.prescriptions_refresh:100: Version: 0.8.0
2022-11-04 13:27:23,167 160015 INFO     thoth.prescriptions_refresh.prescriptions:73: Cloning prescriptions repo 'git@github.com:thoth-station/prescriptions.git'

Will try on cluster and post the updates.

**Comment by harshad16** [comment]
This issue is already fixed by: https://github.com/thoth-station/prescriptions-refresh-job/commit/16079fc22491d690552ad244b1a3f027118cccaf

Also works in cluster:
![Screenshot from 2022-11-04 14-07-23](https://user-images.githubusercontent.com/14028058/200051828-c38227e8-e65c-499f-80b7-618ab6c2ee9e.png)
[prescriptions-refresh-image-analysis-main.log](https://github.com/thoth-station/prescriptions-refresh-job/files/9941214/prescriptions-refresh-image-analysis-main.log)

**Comment by harshad16** [comment]
Thanks for all the work.
closing the issue.
