### ISSUE TITLE
Implement a prescription to notify when a project is archived

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/prescriptions-refresh-job#123]
**Is your feature request related to a problem? Please describe.**
As a consumer of Thoth's prescriptions, I would like to be alerted when a project is archived on GitHub.

**Describe the solution you'd like**
Implement a handler that generates prescriptions to warn about archived packages.

**Comment by fridex** [comment]
I think we have this already implemented - https://github.com/thoth-station/prescriptions-refresh-job/blob/master/thoth/prescriptions_refresh/handlers/gh_archived.py

**Comment by mayaCostantini** [comment]
Right thanks I missed that 👍🏻 Closing the issue
