### ISSUE TITLE
Security Scorecards v3

### ISSUE THREAD

**Issue by fridex** [thoth-station/prescriptions-refresh-job#63]
**Is your feature request related to a problem? Please describe.**

As a user of Thoth, I would like to consume things computed by security scorecards in Thoth recommendations but Thoth's implementation uses old scorecards API that has changed. It should be rewritten to the v3 scorecards implementation.

**Describe the solution you'd like**

- [x] check the current schema of security scorecards available in BigQuery
- [x] rewrite logic that is creating security scorecards prescriptions in prescriptions-refresh job
- [x] make sure the new security scorecards are computed and available to Thoth's adviser in the prescriptions repository

**Comment by fridex** [comment]
Related v4 release, worth to check if they are stable already - https://github.blog/2022-01-19-reducing-security-risk-oss-actions-opensff-scorecards-v4/

**Comment by mayaCostantini** [comment]
Closed by https://github.com/thoth-station/prescriptions-refresh-job/pull/147
